apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentname
  labels:
    foo: bar
    lorem: ipsum
spec:
  replicas: 3
  selector:
    matchLabels:
      foo: bar
      lorem: ipsum
    matchExpressions:
      - {key: a_key, operator: In, values: [a_value]}
      - {key: b_key, operator: NotIn, values: [b_value]}
      - {key: c_key, operator: Exists, values: []}
  template:
    # Same pod structure here
    metadata:
      labels:
        pod_foo: pod_bar
        pod_lorem: pod_ipsum
    spec:
      containers:
      - name: containername
        image: image:version
        ports:
        - containerPort: 80
