apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    foo: bar
    lorem: ipsum
spec:
  replicas: 3
  selector:
    matchLabels:
      foo: bar
    matchExpressions:
      - {key: a_key, operator: In, values: [a_value]}
      - {key: b_key, operator: NotIn, values: [b_value]}
      - {key: c_key, operator: Exists, values: []}
  template:
    metadata:
      labels:
        pod_foo: pod_bar
        pod_lorem: pod_ipsum
    spec:
      containers:
      - name: container_name
        image: image:version
        resources:
          requests:
            cpu: 100m # 0.1 CPU
            memory: 100Mi # ~104MB
          limits:
            cpu: 300m # 0.3 CPU
            memory: 300mi # ~314MB
        env:
        - name: ENV_VAR_NAME
          value: env_var_value
        ports:
        - containerPort: 80
